FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p galina-shimanskaya.com/img && \
    chmod -R 754 /var/www/galina-shimanskaya.com/ && \
    useradd Galina && groupadd Shimanskaya && usermod -aG Shimanskaya Galina && \
    chown -R Galina:Shimanskaya /var/www/galina-shimanskaya.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/galina-shimanskaya.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Galina/g' /etc/nginx/nginx.conf
ADD index.html /var/www/galina-shimanskaya.com/
ADD img.jpg /var/www/galina-shimanskaya.com/img/
CMD ["nginx", "-g", "daemon off;"]
